[package]
name = "perthys/xmlparser"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A intuitive XMLParser entirely implemented in LuaU | https://github.com/Perthys/XMLParser"
license = "MIT"
authors = ["Perthys <perth@perthys.cc>"]
exclude = [
    'ExampleGame.rbxl', 
    '.gitignore',
    'aftman.toml',
    'README.md',
    'code-of-conduct.md',
    'contributing.md',
    'media',
    'old',
    "TestScripts",
]

[dependencies]
